"""Init TokenSymbol and TokenTimeseries tables

Revision ID: b7e23ef12b4c
Revises: 
Create Date: 2025-05-27 19:06:45.464567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7e23ef12b4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('stock', 'index', 'forex', 'futures', 'bitcoin', 'crypto', 'undefined', 'expression', 'spread', 'cfd', 'economic', 'equity', 'dr', 'bond', 'right', 'warrant', 'fund', 'structured', 'commodity', 'fundamental', 'spot', 'swap', 'option', name='tokensymboltype').create(op.get_bind())
    sa.Enum('price', 'volume', name='tokensymbolformat').create(op.get_bind())
    op.create_table('tokensymbol',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('format', postgresql.ENUM('price', 'volume', name='tokensymbolformat', create_type=False), nullable=True),
    sa.Column('listed_exchange', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('minmov', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pricescale', sa.Integer(), nullable=False),
    sa.Column('session', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('type', postgresql.ENUM('stock', 'index', 'forex', 'futures', 'bitcoin', 'crypto', 'undefined', 'expression', 'spread', 'cfd', 'economic', 'equity', 'dr', 'bond', 'right', 'warrant', 'fund', 'structured', 'commodity', 'fundamental', 'spot', 'swap', 'option', name='tokensymboltype', create_type=False), nullable=True),
    sa.PrimaryKeyConstraint('ticker'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('tokentimeseries',
    sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supply', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('price', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('liquidity', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('volume', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['tokensymbol.ticker'], ),
    sa.PrimaryKeyConstraint('time', 'ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokentimeseries')
    op.drop_table('tokensymbol')
    sa.Enum('price', 'volume', name='tokensymbolformat').drop(op.get_bind())
    sa.Enum('stock', 'index', 'forex', 'futures', 'bitcoin', 'crypto', 'undefined', 'expression', 'spread', 'cfd', 'economic', 'equity', 'dr', 'bond', 'right', 'warrant', 'fund', 'structured', 'commodity', 'fundamental', 'spot', 'swap', 'option', name='tokensymboltype').drop(op.get_bind())
    # ### end Alembic commands ###
