run-name: Deploy to Staging
name: Deploy to Staging

on:
    # Action must be defined on default branch before it can be triggered by workflow_dispatch, however, pull_request works.
    push:
    # workflow_dispatch:
