services:
  eve-agent:
    build: 
      context: ./
      dockerfile: ./Dockerfile.eve
    container_name: eve-agent
    volumes:
      - eve-agent:/app/db.sqlite
    platform: linux/amd64
    ports:
      - "8000:80"
      - "5173:5173"
    image: eve-agent:latest
  
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: ./Dockerfile.frontend
    container_name: frontend
    platform: linux/amd64
    ports:
      - "8001:80"
    image: frontend:latest
      


volumes:
  eve-agent:
