services:
  eve-agent:
    env_file: 
      - path: ".env.eve"
        required: false
    build: 
      context: .
      dockerfile: Dockerfile.eve
    container_name: eve-agent
    volumes:
      - eve-agent:/app/db.sqlite
    platform: linux/amd64
    ports:
      - "8000:80"
      - "5173:5173"
    image: eve-agent:latest
  
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: ./Dockerfile.frontend
    container_name: frontend
    platform: linux/amd64
    ports:
      - "8001:80"
    image: frontend:latest
      
  api:
    env_file:
      - path: "apps/api/.env.api"
        required: false  
    build:
      context: apps/api
      dockerfile: ./Dockerfile.api
    container_name: api
    platform: linux/amd64
    image: api:latest
    ports:
      - "80:80"


volumes:
  eve-agent:
