services:
  eve-agent:
    image: eve-agent:latest
    build: 
      context: ./
      dockerfile: ./Dockerfile
    container_name: eve-agent
    volumes:
      - eve-agent:/app/db.sqlite
    ports:
      # - "3000:3000"
      - "80:3069"

volumes:
  eve-agent: