services:
  eve-agent:
    build: 
      context: ./
      dockerfile: ./Dockerfile.eve
    container_name: eve-agent
    volumes:
      - eve-agent:/app/db.sqlite
    platform: linux/amd64
    networks:
      - eve-agent-network

  nginx:
    build:
      context: ./
      dockerfile: ./Dockerfile.nginx
    ports:
      - "80:80"  
    container_name: nginx   
    networks:
      - eve-agent-network


volumes:
  eve-agent:

networks:
  eve-agent-network:
    driver: bridge