services:
  eve-agent:
    build: 
      context: ./
      dockerfile: ./Dockerfile.eve
    container_name: eve-agent
    volumes:
      - eve-agent:/app/db.sqlite
    platform: linux/amd64
    ports:
      - "8000:80"



volumes:
  eve-agent:
