services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: ./Dockerfile.frontend
    container_name: frontend
    platform: linux/amd64
    ports:
      - "8001:80"
      - '9464:9464'
    image: frontend:latest
      
  api:
    env_file: 
      - path: "apps/api/src/.env.api"
        required: false
    build:
      context: apps/api
      dockerfile: ./Dockerfile.api
    container_name: api
    platform: linux/amd64
    image: api:latest
    ports:
      - "8003:80"

  agent-runtime:
    build: 
      # Needs to be in root folder to access the eliza directory
      context: .
      dockerfile: ./apps/runtime/Dockerfile.runtime
    container_name: agent-runtime
    volumes:
      - agent-runtime:/app/eliza/agent/data
    platform: linux/amd64
    image: agent-runtime:latest
    ports:
      - "8002:80"

  prometheus:
    build:
      context: ./apps/prometheus
      dockerfile: ./Dockerfile.prometheus
    container_name: prometheus
    platform: linux/amd64
    image: prometheus:latest
    ports:
      - "9090:9090"

volumes:
  eve-agent:
  agent-runtime: