services:
  eve-agent:
    build: 
      context: ../
      dockerfile: ./Dockerfile.eve
    container_name: eve-agent
    volumes:
      - eve-agent:/app/db.sqlite
    platform: linux/amd64
    ports:
      - "8000:80"
      - "5173:5173"
    image: eve-agent:latest
  api:
    build:
      context: .././apps/api
      dockerfile: ./Dockerfile.api
    container_name: api
    platform: linux/amd64
    image: api:latest


volumes:
  eve-agent:
