FROM python:3.12-bookworm

COPY --from=ghcr.io/astral-sh/uv:0.4.27 /uv /uvx /bin/

WORKDIR /app

COPY . .

RUN uv sync

EXPOSE 80

CMD ["uv", "run", "uvicorn", "src.server:app", "--host", "0.0.0.0", "--port", "80"]