"""Add dynamic_id to user. Separate wallet

Revision ID: 85f4d9b486ae
Revises: fb4810e3c71f
Create Date: 2025-03-10 16:45:17.611288

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = "85f4d9b486ae"
down_revision: Union[str, None] = "fb4810e3c71f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("public_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("public_key_sei", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_key"),
        sa.UniqueConstraint("public_key_sei"),
    )
    op.add_column("user", sa.Column("dynamic_id", sa.Uuid(), nullable=True))
    # Non-nullable dynamic_id is set to zeros_uuid.
    # zeros are meaningless - abopdev and dance users will have dynamic_id manually set to their real values.
    conn = op.get_bind()
    zeros_uuid = "00000000-0000-0000-0000-000000000000"
    conn.execute(text(f"UPDATE user SET dynamic_id = {zeros_uuid} WHERE true;"))
    op.alter_column("user", "dynamic_id", existing_type=sa.Uuid(), nullable=False)

    op.drop_constraint("user_public_key_key", "user", type_="unique")
    op.drop_constraint("user_public_key_sei_key", "user", type_="unique")
    op.create_index(op.f("ix_user_dynamic_id"), "user", ["dynamic_id"], unique=True)
    op.drop_column("user", "public_key")
    op.drop_column("user", "public_key_sei")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("public_key_sei", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user",
        sa.Column("public_key", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_user_dynamic_id"), table_name="user")
    op.create_unique_constraint("user_public_key_sei_key", "user", ["public_key_sei"])
    op.create_unique_constraint("user_public_key_key", "user", ["public_key"])
    op.drop_column("user", "dynamic_id")
    op.drop_table("wallet")
    # ### end Alembic commands ###
