"""Add ABI to Token. Add started field to Runtime

Revision ID: c884a620fdfa
Revises: 2c15509c5199
Create Date: 2025-02-24 16:58:17.506301

"""

import json
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c884a620fdfa"
down_revision: Union[str, None] = "2c15509c5199"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runtime", sa.Column("started", sa.Boolean(), nullable=True))
    op.add_column("token", sa.Column("abi", sa.JSON(), nullable=True))

    # Add an example ABI.
    example_abi = [
        {
            "inputs": [],
            "stateMutability": "nonpayable",
            "type": "constructor",
        }
    ]

    op.execute(
        "INSERT INTO token (abi) VALUES (:abi)", {"abi": json.dumps(example_abi)}
    )

    op.alter_column("token", "abi", existing_type=sa.JSON(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("token", "abi")
    op.drop_column("runtime", "started")
    # ### end Alembic commands ###
