"""empty message

Revision ID: cc2c27d22728
Revises: b07e119f3895
Create Date: 2025-03-17 08:01:18.333338

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc2c27d22728"
down_revision: Union[str, None] = "b07e119f3895"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runtimedeletetask",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("runtime_id", sa.Uuid(), nullable=False),
        sa.Column("celery_task_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("runtime", sa.Column("service_no", sa.Integer(), nullable=False))
    op.add_column(
        "runtime",
        sa.Column("service_arn", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "runtime",
        sa.Column(
            "target_group_arn", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "runtime",
        sa.Column(
            "http_listener_rule_arn", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "runtime",
        sa.Column(
            "https_listener_rule_arn", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runtime", "https_listener_rule_arn")
    op.drop_column("runtime", "http_listener_rule_arn")
    op.drop_column("runtime", "target_group_arn")
    op.drop_column("runtime", "service_arn")
    op.drop_column("runtime", "service_no")
    op.drop_table("runtimedeletetask")
    # ### end Alembic commands ###
