"""empty message

Revision ID: fb4810e3c71f
Revises: c884a620fdfa
Create Date: 2025-02-25 11:13:11.546466

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb4810e3c71f"
down_revision: Union[str, None] = "c884a620fdfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agent", "eliza_agent_id", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agent", "eliza_agent_id", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
