global:
  resolve_timeout: 1m

route:
  receiver: 'slack-notifications'
  group_wait: 0s
  group_interval: 10s
  repeat_interval: 1m

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - send_resolved: true
        username: 'Prometheus'
        channel: '#alerts'
        api_url: 'https://hooks.slack.com/services/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'
        title: '{{ .CommonAnnotations.summary }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Labels.alertname }}  
            *Status:* {{ .Status }}  
            *Instance:* {{ .Labels.instance }}  
            *Summary:* {{ .Annotations.summary }}  
            *Time:* {{ .StartsAt }}
          {{ end }}
