global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

rule_files:
  - /etc/prometheus/alerts.rules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          group: "prometheus"
    basic_auth:
      username: "admin"
      password: "$PROMETHEUS_BASIC_AUTH"

  - job_name: "api"
    scrape_interval: 5s
    metrics_path: /metrics_prometheus
    static_configs:
      - targets: ["host.docker.internal:8003"]
    basic_auth:
      username: "prometheus"
      password: "$PROMETHEUS_BASIC_AUTH"


  # TODO: Add frontend and agent-runtime scrape configs
