FROM python:3.12-bookworm

COPY --from=ghcr.io/astral-sh/uv:0.4.27 /uv /uvx /bin/

WORKDIR /api

COPY . .

RUN uv sync

EXPOSE 80

CMD ["uv", "run", "celery", "-A", "src.tasks", "worker", "--loglevel=info", "--beat"]   