run-name: Deploy frontend to prod
name: Deploy frontend to prod

on:
    workflow_dispatch:

jobs:
    build-and-push-frontend:
        runs-on: ubuntu-latest
        environment: prod/frontend
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2
              with:
                  submodules: "true"

            - name: Configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/AIDEN_GHA_ECR
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              uses: aws-actions/amazon-ecr-login@v2
                
            - name: Create apps/frontend/.env.local
              run: |
                touch apps/frontend/.env.local
                echo NEXT_PUBLIC_DYNAMIC_ENVIRONMENT_ID=292edbc7-9096-4e79-81a6-7ed1e1b7411a >> apps/frontend/.env.local
                echo API_ENDPOINT=https://api.aidn.fun >> apps/frontend/.env.local
                echo AUTH_URL=https://aidn.fun >> apps/frontend/.env.local
                echo NEXT_SEI_NET=main >> apps/frontend/.env.local
                echo NEXT_PUBLIC_BONDING_CONTRACT_ADDRESS=0xDdFF841E7bb9c2180D160eE5E11663ca127Fd21e >> apps/frontend/.env.local

            - name: Build and tag frontend
              run: |
                  make build-frontend

            - name: Push frontend to ECR
              run: |
                  make aws-ecr-push-frontend-prod

    force-redeployment:
        needs: build-and-push-frontend
        runs-on: ubuntu-latest
        steps:
            - name: Configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/AIDEN_GHA_ECS
                  aws-region: us-east-1

            - name: Force redeployment
              run: |
                  aws ecs update-service --cluster Aiden --service aiden-frontend --force-new-deployment

permissions:
    id-token: write
    contents: read
