run-name: Build and push parameterized runtime to staging
name: Build and push parameterized runtime to staging

on:
    workflow_dispatch:
        inputs:
            character_json:
                description: 'The contents of a json file containing the character data'
                required: true
                type: string
            insensitive_env_vars_env:
                description: 'The insensitive environment variables to set for the runtime'
                required: true
                type: string

jobs:
    build-and-push-mairtin:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2
              with:
                submodules: 'true'
            
            - name: Write character json to a file
              run: echo "${{ inputs.character_json }}" > character.json
            
            - name: Write insensitive env vars to a file
              run: echo "${{ inputs.insensitive_env_vars_env }}" > .env

            - name: Configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/AIDEN_GHA_ECR
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              uses: aws-actions/amazon-ecr-login@v2

            - name: Create registry if DNE
              run: |
                
            - name: Build eve, tag it, and push it to ECR
              run: |
                  make build-eve
                  make aws-ecr-push-eve

# Required for GitHub's OIDC provider 
# https://github.com/aws-actions/configure-aws-credentials?tab=readme-ov-file#oidc
permissions:
    id-token: write
    contents: read