run-name: Deploy frontend to prod
name: Deploy frontend to prod

on:
    workflow_dispatch:

jobs:
    force-redeployment:
        runs-on: ubuntu-latest
        steps:
            - name: Configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/AIDEN_GHA_ECS
                  aws-region: us-east-1

            - name: Force redeployment
              run: |
                  aws ecs update-service --cluster Aiden --service aiden-frontend --force-new-deployment

permissions:
    id-token: write
    contents: read
