run-name: Deploy Aiden API to Staging
name: Deploy Aiden API to Staging

on:
    workflow_dispatch:

jobs:
    build-and-push-aiden:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2
              with:
                submodules: 'true'
            
            - name: Configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/AIDEN_GHA_ECR
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              uses: aws-actions/amazon-ecr-login@v2
            
            - name: Build and tag api
              run: |
                make build-api
            
            - name: Push api to ECR
              run: |
                make aws-ecr-push-api

            - name: Build and tag celery worker
              run:
                make build-celery
            
            - name: Push celery worker to ECR
              run:
                make aws-ecr-push-celery
    
      
    force-redeployment:
      needs: build-and-push-aiden
      runs-on: ubuntu-latest
      steps:
        - name: Configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
              role-to-assume: arn:aws:iam::008971649127:role/AIDEN_GHA_ECS 
              aws-region: us-east-1

        - name: Force redeployment
          run: |
            aws ecs update-service --cluster AidenStaging --service aiden-api-staging --force-new-deployment

# Required for GitHub's OIDC provider 
# https://github.com/aws-actions/configure-aws-credentials?tab=readme-ov-file#oidc
permissions:
    id-token: write
    contents: read